import { Link, useNavigate } from 'react-router-dom';
import { Leaf, LockKeyhole, Mail } from 'lucide-react';
import { useForm } from 'react-hook-form';
import toast from 'react-hot-toast';
import api from '../lib/api';
import { useAuth } from '../context/AuthContext';

export default function LoginPage() {
  const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm(); const { login } = useAuth(); const navigate = useNavigate();
  const submit = async (values) => { try { const { data } = await api.post('/auth/login', values); login(data.data); toast.success('Welcome back to your farm dashboard'); navigate('/'); } catch (error) { toast.error(error.response?.data?.message || 'Unable to sign in'); } };
  return <main className="grid min-h-screen bg-forest-50 lg:grid-cols-2"><section className="hidden bg-cover bg-center p-12 lg:flex lg:flex-col lg:justify-between" style={{ backgroundImage: "linear-gradient(90deg, rgba(11,53,30,.84), rgba(11,53,30,.46)), url('/farm-landscape.png')" }}><div className="flex items-center gap-3 text-white"><span className="grid h-10 w-10 place-items-center rounded-lg bg-white/15"><Leaf /></span><span className="font-bold">Digital Krishi Mytra</span></div><div className="max-w-lg text-white"><p className="text-4xl font-bold leading-tight">Practical farm intelligence for every decision.</p><p className="mt-4 text-base text-white/80">Use weather, crop, scheme and community signals to plan a stronger season.</p></div><p className="text-xs text-white/65">Built for Indian farmers, one field at a time.</p></section><section className="flex items-center justify-center p-6"><div className="w-full max-w-md"><Link to="/" className="mb-10 flex items-center gap-2 font-bold text-forest-700 lg:hidden"><Leaf /> Digital Krishi Mytra</Link><h1 className="text-3xl font-bold text-slate-900">Welcome back</h1><p className="mt-2 text-sm text-slate-500">Sign in to see what your farm needs today.</p><form className="mt-8 space-y-5" onSubmit={handleSubmit(submit)}><label><span className="field-label">Email address</span><span className="relative block"><Mail className="absolute left-3 top-3 text-slate-400" size={18} /><input className="field pl-10" type="email" placeholder="you@example.com" {...register('email', { required: 'Email is required' })} /></span>{errors.email && <small className="mt-1 block text-clay-600">{errors.email.message}</small>}</label><label><span className="field-label">Password</span><span className="relative block"><LockKeyhole className="absolute left-3 top-3 text-slate-400" size={18} /><input className="field pl-10" type="password" placeholder="Your password" {...register('password', { required: 'Password is required' })} /></span>{errors.password && <small className="mt-1 block text-clay-600">{errors.password.message}</small>}</label><div className="flex justify-end"><Link to="/forgot-password" className="text-xs font-medium text-forest-700 hover:underline">Forgot password?</Link></div><button disabled={isSubmitting} className="btn-primary w-full">{isSubmitting ? 'Signing in...' : 'Sign in'}</button></form><p className="mt-6 text-center text-sm text-slate-500">New to Krishi Mytra? <Link className="font-semibold text-forest-700 hover:underline" to="/register">Create your account</Link></p></div></section></main>;
}
